### ISSUE TITLE
Does it conform to any standards?

### ISSUE THREAD

**Issue by Euphorbium** [blag/django-secure-mail#5]
For example https://tools.ietf.org/html/rfc5751 or https://tools.ietf.org/html/rfc1847 If it does, mention that in the docs.

**Comment by blag** [comment]
This is really a question about python-gnupg. And since 'S/MIME' isn't found anywhere in that codebase, I would guess that it isn't S/MIME compatible. It is compatible with OpenPGP though.

I would be interested in a PR that implemented this, although S/MIME is not quite the same use case as OpenPGP.
